Export naxsi variables
nbs-system/naxsi pull request #574
Opened 2021-11-16 15:09 UTC by theobarrague

Same as #388 but I've made some modifications to work with current naxsi version.

2021-11-16 18:08 UTC, wargio requested changes

2022-07-22 11:14 UTC, theobarrague commented
Changes were made, can you check ?

2022-07-22 13:07 UTC, wargio commented
Can you please submit your PR here https://github.com/wargio/naxsi ?

2022-09-01 20:38 UTC, wargio commented
Merged in https://github.com/wargio/naxsi/pull/24

2022-09-01 20:38 UTC, closed without merging